ftp:
  local_dirs:
  - download/SVDNB
  passive_mode: true
  password: anonymous@
  pattern: .*\.xml$
  remote_dirs:
  - 20200301/VIIRS-SDR/VIIRS-Day-Night-Band-SDR/NPP
  url: ftp-npp.bou.class.noaa.gov
  username: anonymous
