ftp:
  url: ftp-npp.bou.class.noaa.gov
  username: anonymous
  password: null
  # passive_mode: no
  passive_mode: yes
  # type: noaa
  day_before: 2
  remote_dirs:
    - 20200301/VIIRS-SDR/VIIRS-Day-Night-Band-SDR/NPP
    # - VIIRS-SDR/VIIRS-Moderate-Bands-SDR-Geo/NPP
    # - VIIRS-SDR/VIIRS-Day-Night-Band-SDR-Ellipsoid-Geo/NPP
    # - VIIRS-EDR/VIIRS-Cloud-Mask-EDR/NPP
  base_dir: download/noaa
  local_dirs:
    - SVDNB
    - GMODO
    - GDNBO
    - VICMO
  dest_dir: D:\ul19_data\noaa
  # dir_pattern:
  #   - NPP
  dir_pattern: null
  pattern: 
    - .*\.xml$
  #pattern: null
  overwrite: no
  #overwrite: yes