# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main/python/ui/config.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 652)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelHost = QtWidgets.QLabel(Dialog)
        self.labelHost.setObjectName("labelHost")
        self.gridLayout.addWidget(self.labelHost, 0, 0, 1, 1)
        self.lineEditHost = QtWidgets.QLineEdit(Dialog)
        self.lineEditHost.setObjectName("lineEditHost")
        self.gridLayout.addWidget(self.lineEditHost, 0, 1, 1, 1)
        self.labelUsername = QtWidgets.QLabel(Dialog)
        self.labelUsername.setObjectName("labelUsername")
        self.gridLayout.addWidget(self.labelUsername, 1, 0, 1, 1)
        self.lineEditUsername = QtWidgets.QLineEdit(Dialog)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.gridLayout.addWidget(self.lineEditUsername, 1, 1, 1, 1)
        self.labelPassword = QtWidgets.QLabel(Dialog)
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout.addWidget(self.labelPassword, 2, 0, 1, 1)
        self.lineEditPassword = QtWidgets.QLineEdit(Dialog)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout.addWidget(self.lineEditPassword, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTransferMode = QtWidgets.QLabel(Dialog)
        self.labelTransferMode.setObjectName("labelTransferMode")
        self.verticalLayout.addWidget(self.labelTransferMode)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonDefault = QtWidgets.QRadioButton(Dialog)
        self.radioButtonDefault.setObjectName("radioButtonDefault")
        self.horizontalLayout.addWidget(self.radioButtonDefault)
        self.radioButtonActive = QtWidgets.QRadioButton(Dialog)
        self.radioButtonActive.setObjectName("radioButtonActive")
        self.horizontalLayout.addWidget(self.radioButtonActive)
        self.radioButtonPassive = QtWidgets.QRadioButton(Dialog)
        self.radioButtonPassive.setObjectName("radioButtonPassive")
        self.horizontalLayout.addWidget(self.radioButtonPassive)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 2)
        self.labelRemoteDirs = QtWidgets.QLabel(Dialog)
        self.labelRemoteDirs.setObjectName("labelRemoteDirs")
        self.gridLayout.addWidget(self.labelRemoteDirs, 4, 0, 1, 1)
        self.textEditRemoteDirs = QtWidgets.QTextEdit(Dialog)
        self.textEditRemoteDirs.setObjectName("textEditRemoteDirs")
        self.gridLayout.addWidget(self.textEditRemoteDirs, 4, 1, 1, 1)
        self.labelLocalDirs = QtWidgets.QLabel(Dialog)
        self.labelLocalDirs.setObjectName("labelLocalDirs")
        self.gridLayout.addWidget(self.labelLocalDirs, 5, 0, 1, 1)
        self.textEditLocalDirs = QtWidgets.QTextEdit(Dialog)
        self.textEditLocalDirs.setObjectName("textEditLocalDirs")
        self.gridLayout.addWidget(self.textEditLocalDirs, 5, 1, 1, 1)
        self.labelFilePattern = QtWidgets.QLabel(Dialog)
        self.labelFilePattern.setObjectName("labelFilePattern")
        self.gridLayout.addWidget(self.labelFilePattern, 6, 0, 1, 1)
        self.lineEditFilePattern = QtWidgets.QLineEdit(Dialog)
        self.lineEditFilePattern.setObjectName("lineEditFilePattern")
        self.gridLayout.addWidget(self.lineEditFilePattern, 6, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelHost.setText(_translate("Dialog", "Host"))
        self.labelUsername.setText(_translate("Dialog", "Username"))
        self.labelPassword.setText(_translate("Dialog", "Password"))
        self.labelTransferMode.setText(_translate("Dialog", "TransferMode:"))
        self.radioButtonDefault.setText(_translate("Dialog", "Default"))
        self.radioButtonActive.setText(_translate("Dialog", "Active"))
        self.radioButtonPassive.setText(_translate("Dialog", "Passive"))
        self.labelRemoteDirs.setText(_translate("Dialog", "Remote Dirs"))
        self.labelLocalDirs.setText(_translate("Dialog", "Local Dirs"))
        self.labelFilePattern.setText(_translate("Dialog", "File Pattern"))
