# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(431, 686)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelHost = QtWidgets.QLabel(Dialog)
        self.labelHost.setObjectName("labelHost")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelHost)
        self.lineEditHost = QtWidgets.QLineEdit(Dialog)
        self.lineEditHost.setObjectName("lineEditHost")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditHost)
        self.labelUsername = QtWidgets.QLabel(Dialog)
        self.labelUsername.setObjectName("labelUsername")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelUsername)
        self.lineEditUsername = QtWidgets.QLineEdit(Dialog)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditUsername)
        self.labelPassword = QtWidgets.QLabel(Dialog)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(Dialog)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditPassword)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTransferMode = QtWidgets.QLabel(Dialog)
        self.labelTransferMode.setObjectName("labelTransferMode")
        self.verticalLayout.addWidget(self.labelTransferMode)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonDefault = QtWidgets.QRadioButton(Dialog)
        self.radioButtonDefault.setObjectName("radioButtonDefault")
        self.horizontalLayout.addWidget(self.radioButtonDefault)
        self.radioButtonActive = QtWidgets.QRadioButton(Dialog)
        self.radioButtonActive.setObjectName("radioButtonActive")
        self.horizontalLayout.addWidget(self.radioButtonActive)
        self.radioButtonPassive = QtWidgets.QRadioButton(Dialog)
        self.radioButtonPassive.setObjectName("radioButtonPassive")
        self.horizontalLayout.addWidget(self.radioButtonPassive)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout)
        self.labelRemoteDirs = QtWidgets.QLabel(Dialog)
        self.labelRemoteDirs.setObjectName("labelRemoteDirs")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelRemoteDirs)
        self.textEditRemoteDirs = QtWidgets.QTextEdit(Dialog)
        self.textEditRemoteDirs.setObjectName("textEditRemoteDirs")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.textEditRemoteDirs)
        self.labelBaseDir = QtWidgets.QLabel(Dialog)
        self.labelBaseDir.setObjectName("labelBaseDir")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelBaseDir)
        self.lineEditBaseDir = QtWidgets.QLineEdit(Dialog)
        self.lineEditBaseDir.setObjectName("lineEditBaseDir")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditBaseDir)
        self.textEditLocalDirs = QtWidgets.QTextEdit(Dialog)
        self.textEditLocalDirs.setObjectName("textEditLocalDirs")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.textEditLocalDirs)
        self.labelFilePattern = QtWidgets.QLabel(Dialog)
        self.labelFilePattern.setObjectName("labelFilePattern")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.labelFilePattern)
        self.lineEditFilePattern = QtWidgets.QLineEdit(Dialog)
        self.lineEditFilePattern.setObjectName("lineEditFilePattern")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEditFilePattern)
        self.lineEditDestDir = QtWidgets.QLineEdit(Dialog)
        self.lineEditDestDir.setObjectName("lineEditDestDir")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEditDestDir)
        self.labelLocalDirs = QtWidgets.QLabel(Dialog)
        self.labelLocalDirs.setObjectName("labelLocalDirs")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelLocalDirs)
        self.labelDestDir = QtWidgets.QLabel(Dialog)
        self.labelDestDir.setObjectName("labelDestDir")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelDestDir)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelHost.setText(_translate("Dialog", "Host"))
        self.labelUsername.setText(_translate("Dialog", "Username"))
        self.labelPassword.setText(_translate("Dialog", "Password"))
        self.labelTransferMode.setText(_translate("Dialog", "TransferMode:"))
        self.radioButtonDefault.setText(_translate("Dialog", "Default"))
        self.radioButtonActive.setText(_translate("Dialog", "Active"))
        self.radioButtonPassive.setText(_translate("Dialog", "Passive"))
        self.labelRemoteDirs.setText(_translate("Dialog", "Remote Dirs"))
        self.labelBaseDir.setText(_translate("Dialog", "Base Dir"))
        self.labelFilePattern.setText(_translate("Dialog", "File Pattern"))
        self.labelLocalDirs.setText(_translate("Dialog", "Local Dirs"))
        self.labelDestDir.setText(_translate("Dialog", "Dest Dir"))
