# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelHost = QtWidgets.QLabel(self.centralwidget)
        self.labelHost.setObjectName("labelHost")
        self.horizontalLayout.addWidget(self.labelHost)
        self.lineEditHost = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditHost.setObjectName("lineEditHost")
        self.horizontalLayout.addWidget(self.lineEditHost)
        self.labelUser = QtWidgets.QLabel(self.centralwidget)
        self.labelUser.setObjectName("labelUser")
        self.horizontalLayout.addWidget(self.labelUser)
        self.lineEditUser = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUser.setObjectName("lineEditUser")
        self.horizontalLayout.addWidget(self.lineEditUser)
        self.labelPassword = QtWidgets.QLabel(self.centralwidget)
        self.labelPassword.setObjectName("labelPassword")
        self.horizontalLayout.addWidget(self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.horizontalLayout.addWidget(self.lineEditPassword)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelFileToDownload = QtWidgets.QLabel(self.centralwidget)
        self.labelFileToDownload.setObjectName("labelFileToDownload")
        self.verticalLayout.addWidget(self.labelFileToDownload)
        self.listViewFileToDownload = QtWidgets.QListView(self.centralwidget)
        self.listViewFileToDownload.setObjectName("listViewFileToDownload")
        self.verticalLayout.addWidget(self.listViewFileToDownload)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelDownloadComplete = QtWidgets.QLabel(self.centralwidget)
        self.labelDownloadComplete.setObjectName("labelDownloadComplete")
        self.verticalLayout_2.addWidget(self.labelDownloadComplete)
        self.listViewDownloadComplete = QtWidgets.QListView(self.centralwidget)
        self.listViewDownloadComplete.setObjectName("listViewDownloadComplete")
        self.verticalLayout_2.addWidget(self.listViewDownloadComplete)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(400, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonDownload = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDownload.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.horizontalLayout_3.addWidget(self.pushButtonDownload)
        self.pushButtonCancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_3.addWidget(self.pushButtonCancel)
        self.pushButtonApply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonApply.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.horizontalLayout_3.addWidget(self.pushButtonApply)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConfig = QtWidgets.QAction(MainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.menuFile.addAction(self.actionConfig)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FileDown"))
        self.labelHost.setText(_translate("MainWindow", "Host: "))
        self.labelUser.setText(_translate("MainWindow", "User: "))
        self.labelPassword.setText(_translate("MainWindow", "Password: "))
        self.labelFileToDownload.setText(_translate("MainWindow", "File To Download"))
        self.labelDownloadComplete.setText(_translate("MainWindow", "Download Complete"))
        self.pushButtonDownload.setText(_translate("MainWindow", "Download"))
        self.pushButtonCancel.setText(_translate("MainWindow", "Cancel"))
        self.pushButtonApply.setText(_translate("MainWindow", "Apply"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionConfig.setText(_translate("MainWindow", "Config"))
